"""MockJobSource — returns a static set of realistic Vietnamese IT jobs."""

from app.modules.jobs.schema import JobCreate
from app.modules.jobs.sources.base import BaseJobSource

_MOCK_JOBS: list[dict] = [
    # ── Backend ──────────────────────────────────────────────
    {
        "title": "Backend Developer (Python/FastAPI)",
        "company_name": "FPT Software",
        "company_logo_url": "https://logo.clearbit.com/fpt-software.com",
        "location": "Hà Nội",
        "salary_text": "20 - 35 triệu",
        "salary_min": 20000000,
        "salary_max": 35000000,
        "skills": ["Python", "FastAPI", "PostgreSQL", "Docker", "Redis"],
        "description": "Phát triển và duy trì các API backend cho nền tảng tuyển dụng IT sử dụng FastAPI. Làm việc với PostgreSQL và Redis để đảm bảo hiệu năng cao.",
        "requirements": "Tối thiểu 2 năm kinh nghiệm với Python. Thành thạo FastAPI hoặc Django. Có kinh nghiệm với PostgreSQL và Docker.",
        "benefits": "Lương tháng 13, bảo hiểm sức khỏe, làm việc hybrid, team building hàng quý.",
        "deadline": "2026-07-15",
        "source_name": "Mock",
    },
    {
        "title": "Senior Backend Developer (Go)",
        "company_name": "VNG Corporation",
        "company_logo_url": "https://logo.clearbit.com/vng.com.vn",
        "location": "TP. Hồ Chí Minh",
        "salary_text": "40 - 60 triệu",
        "salary_min": 40000000,
        "salary_max": 60000000,
        "skills": ["Go", "gRPC", "PostgreSQL", "Kubernetes", "Kafka"],
        "description": "Thiết kế và triển khai kiến trúc microservices cho nền tảng ZaloPay sử dụng Go và gRPC. Xử lý hàng triệu giao dịch mỗi ngày.",
        "requirements": "Tối thiểu 5 năm kinh nghiệm backend. Thành thạo Go. Có kinh nghiệm với hệ thống phân tán, message queue, Kubernetes.",
        "benefits": "Cổ phiếu công ty, bảo hiểm toàn diện, phụ cấp ăn trưa, gym miễn phí.",
        "deadline": "2026-08-01",
        "source_name": "Mock",
    },
    # ── Frontend ─────────────────────────────────────────────
    {
        "title": "Frontend Developer (React/TypeScript)",
        "company_name": "Tiki Corporation",
        "company_logo_url": "https://logo.clearbit.com/tiki.vn",
        "location": "TP. Hồ Chí Minh",
        "salary_text": "25 - 40 triệu",
        "salary_min": 25000000,
        "salary_max": 40000000,
        "skills": ["React", "TypeScript", "Next.js", "Tailwind CSS", "Redux"],
        "description": "Xây dựng giao diện người dùng cho nền tảng thương mại điện tử Tiki với hàng triệu người dùng. Tập trung vào hiệu năng và trải nghiệm người dùng.",
        "requirements": "Tối thiểu 3 năm kinh nghiệm React. Thành thạo TypeScript. Có kinh nghiệm với Next.js và SSR.",
        "benefits": "Lương tháng 13, bảo hiểm, môi trường làm việc năng động, cơ hội thăng tiến.",
        "deadline": "2026-07-20",
        "source_name": "Mock",
    },
    {
        "title": "React Native Developer",
        "company_name": "VieConnect",
        "company_logo_url": "https://logo.clearbit.com/vieconnect.vn",
        "location": "Đà Nẵng",
        "salary_text": "18 - 30 triệu",
        "salary_min": 18000000,
        "salary_max": 30000000,
        "skills": ["React Native", "TypeScript", "Redux Toolkit", "Firebase", "REST API"],
        "description": "Phát triển ứng dụng di động ViecConnect cho iOS và Android bằng React Native. Tích hợp API backend và Firebase cho push notification.",
        "requirements": "Tối thiểu 2 năm kinh nghiệm React Native. Đã publish ít nhất 1 app lên App Store hoặc Google Play.",
        "benefits": "Làm việc từ xa 3 ngày/tuần, bảo hiểm, MacBook Pro.",
        "deadline": "2026-07-30",
        "source_name": "Mock",
    },
    # ── Fullstack ────────────────────────────────────────────
    {
        "title": "Fullstack Developer (Node.js/React)",
        "company_name": "Shopee Vietnam",
        "company_logo_url": "https://logo.clearbit.com/shopee.vn",
        "location": "TP. Hồ Chí Minh",
        "salary_text": "30 - 50 triệu",
        "salary_min": 30000000,
        "salary_max": 50000000,
        "skills": ["Node.js", "React", "TypeScript", "MongoDB", "AWS"],
        "description": "Phát triển các tính năng fullstack cho hệ thống quản lý người bán hàng Shopee. Xây dựng admin dashboard và API tích hợp.",
        "requirements": "Tối thiểu 3 năm kinh nghiệm fullstack. Thành thạo Node.js và React. Có kinh nghiệm với AWS (EC2, S3, Lambda).",
        "benefits": "Bảo hiểm toàn diện, thưởng hiệu suất, học phí đào tạo, du lịch hàng năm.",
        "deadline": "2026-07-25",
        "source_name": "Mock",
    },
    {
        "title": "Fullstack Developer (Python/Django)",
        "company_name": "MoMo (M_Service)",
        "company_logo_url": "https://logo.clearbit.com/momo.vn",
        "location": "TP. Hồ Chí Minh",
        "salary_text": "35 - 50 triệu",
        "salary_min": 35000000,
        "salary_max": 50000000,
        "skills": ["Python", "Django", "React", "PostgreSQL", "Docker"],
        "description": "Tham gia phát triển nền tảng ví điện tử MoMo. Xây dựng API thanh toán và trang quản lý nội bộ.",
        "requirements": "Tối thiểu 3 năm kinh nghiệm Python/Django. Kiến thức về bảo mật tài chính là lợi thế.",
        "benefits": "Thưởng cổ phiếu ESOP, bảo hiểm FPT Care, teambuilding hàng quý.",
        "deadline": "2026-08-10",
        "source_name": "Mock",
    },
    # ── Data & AI ────────────────────────────────────────────
    {
        "title": "Data Engineer",
        "company_name": "Zalo (VNG)",
        "company_logo_url": "https://logo.clearbit.com/zalo.me",
        "location": "TP. Hồ Chí Minh",
        "salary_text": "35 - 55 triệu",
        "salary_min": 35000000,
        "salary_max": 55000000,
        "skills": ["Python", "Apache Spark", "Airflow", "PostgreSQL", "AWS"],
        "description": "Xây dựng và duy trì pipeline dữ liệu cho hàng petabytes dữ liệu người dùng Zalo. Thiết kế data warehouse và ETL processes.",
        "requirements": "Tối thiểu 3 năm kinh nghiệm Data Engineering. Thành thạo Spark và Airflow. Có kinh nghiệm với AWS data services.",
        "benefits": "Lương cạnh tranh, cổ phiếu, bảo hiểm, môi trường R&D mạnh.",
        "deadline": "2026-08-15",
        "source_name": "Mock",
    },
    {
        "title": "AI/ML Engineer",
        "company_name": "VIN AI Research",
        "company_logo_url": "https://logo.clearbit.com/vinbigdata.org",
        "location": "Hà Nội",
        "salary_text": "40 - 65 triệu",
        "salary_min": 40000000,
        "salary_max": 65000000,
        "skills": ["Python", "PyTorch", "Transformers", "MLflow", "CUDA"],
        "description": "Nghiên cứu và phát triển các mô hình AI cho xử lý ngôn ngữ tiếng Việt. Fine-tune LLMs cho các ứng dụng thực tế.",
        "requirements": "Thạc sĩ hoặc Tiến sĩ ngành AI/ML. Có kinh nghiệm với Transformers và fine-tuning LLMs. Có publication tại hội nghị AI uy tín là lợi thế.",
        "benefits": "Lương cạnh tranh, phòng lab hiện đại, tham dự hội nghị quốc tế, tài trợ học phí.",
        "deadline": "2026-09-01",
        "source_name": "Mock",
    },
    {
        "title": "Data Analyst",
        "company_name": "Techcombank",
        "company_logo_url": "https://logo.clearbit.com/techcombank.com.vn",
        "location": "Hà Nội",
        "salary_text": "20 - 35 triệu",
        "salary_min": 20000000,
        "salary_max": 35000000,
        "skills": ["SQL", "Python", "Power BI", "Excel", "Statistics"],
        "description": "Phân tích dữ liệu khách hàng và giao dịch ngân hàng. Xây dựng dashboard báo cáo kinh doanh bằng Power BI.",
        "requirements": "Tối thiểu 2 năm kinh nghiệm phân tích dữ liệu. Thành thạo SQL và Python. Có kinh nghiệm với Power BI hoặc Tableau.",
        "benefits": "Chế độ ngân hàng, bảo hiểm, đào tạo chuyên môn, thăng tiến rõ ràng.",
        "deadline": "2026-07-10",
        "source_name": "Mock",
    },
    # ── QA ───────────────────────────────────────────────────
    {
        "title": "QA Engineer (Automation)",
        "company_name": "KMS Technology",
        "company_logo_url": "https://logo.clearbit.com/kms-technology.com",
        "location": "TP. Hồ Chí Minh",
        "salary_text": "18 - 30 triệu",
        "salary_min": 18000000,
        "salary_max": 30000000,
        "skills": ["Selenium", "Python", "Cypress", "CI/CD", "API Testing"],
        "description": "Xây dựng framework kiểm thử tự động cho các ứng dụng web và mobile. Thiết kế test case và tích hợp vào CI/CD pipeline.",
        "requirements": "Tối thiểu 2 năm kinh nghiệm QA Automation. Thành thạo Selenium hoặc Cypress. Biết Python cho automation scripting.",
        "benefits": "Môi trường Agile chuyên nghiệp, đào tạo ISTQB, lương tháng 13.",
        "deadline": "2026-07-18",
        "source_name": "Mock",
    },
    {
        "title": "Senior QA/QC Lead",
        "company_name": "VNG Corporation",
        "company_logo_url": "https://logo.clearbit.com/vng.com.vn",
        "location": "TP. Hồ Chí Minh",
        "salary_text": "35 - 45 triệu",
        "salary_min": 35000000,
        "salary_max": 45000000,
        "skills": ["Test Strategy", "Selenium", "JMeter", "Python", "Docker"],
        "description": "Dẫn dắt đội QA 8 người cho các sản phẩm Zalo. Xây dựng chiến lược kiểm thử tự động và performance testing.",
        "requirements": "Tối thiểu 5 năm kinh nghiệm QA, trong đó 2 năm làm lead. Thành thạo automation và performance testing. Chứng chỉ ISTQB Advanced là lợi thế.",
        "benefits": "Cổ phiếu ESOP, bảo hiểm toàn diện, laptop mới hàng năm.",
        "deadline": "2026-08-05",
        "source_name": "Mock",
    },
    # ── DevOps ──────────────────────────────────────────────
    {
        "title": "DevOps Engineer",
        "company_name": "FPT Software",
        "company_logo_url": "https://logo.clearbit.com/fpt-software.com",
        "location": "Đà Nẵng",
        "salary_text": "25 - 40 triệu",
        "salary_min": 25000000,
        "salary_max": 40000000,
        "skills": ["Docker", "Kubernetes", "AWS", "Terraform", "CI/CD"],
        "description": "Quản lý hạ tầng cloud trên AWS cho các dự án outsourcing lớn. Thiết lập Kubernetes cluster và monitoring với Prometheus/Grafana.",
        "requirements": "Tối thiểu 3 năm kinh nghiệm DevOps. Chứng chỉ AWS Solutions Architect. Thành thạo Kubernetes và Terraform.",
        "benefits": "Lương tháng 13, chứng chỉ AWS miễn phí, làm việc tại Đà Nẵng.",
        "deadline": "2026-07-22",
        "source_name": "Mock",
    },
    {
        "title": "Cloud Infrastructure Engineer",
        "company_name": "VNPT IT",
        "company_logo_url": "https://logo.clearbit.com/vnpt.com.vn",
        "location": "Hà Nội",
        "salary_text": "22 - 35 triệu",
        "salary_min": 22000000,
        "salary_max": 35000000,
        "skills": ["AWS", "GCP", "Terraform", "Ansible", "Linux"],
        "description": "Thiết kế và triển khai hạ tầng đám mây cho các dịch vụ chính phủ điện tử. Đảm bảo SLA 99.9% và bảo mật hệ thống.",
        "requirements": "Tối thiểu 3 năm kinh nghiệm cloud. Chứng chỉ AWS hoặc GCP. Kinh nghiệm với các dự án chính phủ là lợi thế.",
        "benefits": "Chế độ nhà nước, phụ cấp, đào tạo chứng chỉ cloud.",
        "deadline": "2026-08-20",
        "source_name": "Mock",
    },
    # ── Other ───────────────────────────────────────────────
    {
        "title": "Solution Architect",
        "company_name": "NashTech",
        "company_logo_url": "https://logo.clearbit.com/nashtechglobal.com",
        "location": "TP. Hồ Chí Minh",
        "salary_text": "45 - 65 triệu",
        "salary_min": 45000000,
        "salary_max": 65000000,
        "skills": ["AWS", "Microservices", "Java", "Node.js", "Architecture Design"],
        "description": "Thiết kế kiến trúc giải pháp cho các dự án enterprise. Làm việc trực tiếp với khách hàng quốc tế để đưa ra giải pháp kỹ thuật tối ưu.",
        "requirements": "Tối thiểu 7 năm kinh nghiệm CNTT. Chứng chỉ AWS Solutions Architect Professional. Tiếng Anh xuất sắc.",
        "benefits": "Lương cạnh tranh, onsite Anh/Úc, bảo hiểm quốc tế, xe đưa đón.",
        "deadline": "2026-09-20",
        "source_name": "Mock",
    },
    # ── Mobile ───────────────────────────────────────────────
    {
        "title": "iOS Developer (Swift)",
        "company_name": "VieConnect",
        "company_logo_url": "https://logo.clearbit.com/vieconnect.vn",
        "location": "Remote",
        "salary_text": "20 - 35 triệu",
        "salary_min": 20000000,
        "salary_max": 35000000,
        "skills": ["Swift", "UIKit", "SwiftUI", "CoreData", "XCTest"],
        "description": "Phát triển ứng dụng iOS cho nền tảng tuyển dụng ViecConnect. Xây dựng giao diện người dùng bằng SwiftUI và UIKit.",
        "requirements": "Tối thiểu 2 năm kinh nghiệm iOS. Thành thạo Swift và SwiftUI. Đã có app trên App Store.",
        "benefits": "Làm việc remote hoàn toàn, lương cạnh tranh, MacBook Pro, health insurance.",
        "deadline": "2026-07-28",
        "source_name": "Mock",
    },
    {
        "title": "Android Developer (Kotlin)",
        "company_name": "TIKI Corporation",
        "company_logo_url": "https://logo.clearbit.com/tiki.vn",
        "location": "TP. Hồ Chí Minh",
        "salary_text": "22 - 35 triệu",
        "salary_min": 22000000,
        "salary_max": 35000000,
        "skills": ["Kotlin", "Jetpack Compose", "Coroutines", "Room DB", "Retrofit"],
        "description": "Phát triển ứng dụng Tiki cho Android với Jetpack Compose. Tối ưu hiệu năng cho hàng triệu người dùng.",
        "requirements": "Tối thiểu 3 năm kinh nghiệm Android. Thành thạo Kotlin và Jetpack Compose. Có kinh nghiệm với ứng dụng quy mô lớn.",
        "benefits": "Lương tháng 13, môi trường startup, team trẻ năng động.",
        "deadline": "2026-08-12",
        "source_name": "Mock",
    },
    # ── Security / Other ─────────────────────────────────────
    {
        "title": "CyberSecurity Engineer",
        "company_name": "CMC Cyber Security",
        "company_logo_url": "https://logo.clearbit.com/cmc.com.vn",
        "location": "Hà Nội",
        "salary_text": "30 - 50 triệu",
        "salary_min": 30000000,
        "salary_max": 50000000,
        "skills": ["Penetration Testing", "Python", "Wireshark", "SIEM", "OWASP"],
        "description": "Thực hiện penetration testing và bảo mật hệ thống cho các khách hàng doanh nghiệp. Phát hiện và khắc phục lỗ hổng bảo mật.",
        "requirements": "Chứng chỉ CEH/OSCP. Tối thiểu 3 năm kinh nghiệm an ninh mạng. Thành thạo các công cụ pentesting.",
        "benefits": "Lương cạnh tranh, chứng chỉ bảo mật được tài trợ, làm việc với chuyên gia.",
        "deadline": "2026-09-15",
        "source_name": "Mock",
    },
    {
        "title": "IT Project Manager",
        "company_name": "FPT Software",
        "company_logo_url": "https://logo.clearbit.com/fpt-software.com",
        "location": "Đà Nẵng",
        "salary_text": "30 - 45 triệu",
        "salary_min": 30000000,
        "salary_max": 45000000,
        "skills": ["Agile", "Scrum", "JIRA", "Risk Management", "English"],
        "description": "Quản lý các dự án phần mềm cho khách hàng Nhật Bản. Lập kế hoạch, theo dõi tiến độ và quản lý rủi ro dự án.",
        "requirements": "Tối thiểu 5 năm kinh nghiệm quản lý dự án CNTT. Chứng chỉ PMP hoặc Scrum Master. Tiếng Anh hoặc tiếng Nhật giao tiếp tốt.",
        "benefits": "Cơ hội onsite Nhật Bản, lương tháng 14, đào tạo PMP.",
        "deadline": "2026-08-25",
        "source_name": "Mock",
    },
]


class MockJobSource(BaseJobSource):
    """Returns a static collection of realistic Vietnamese IT job listings."""

    @property
    def source_name(self) -> str:
        return "Mock"

    def fetch_jobs(self) -> list[JobCreate]:
        """Return 18 curated IT job payloads covering 8 categories."""
        jobs: list[JobCreate] = []
        for raw in _MOCK_JOBS:
            jobs.append(JobCreate(**raw))
        return jobs
